// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/v1/auth.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AccessToken with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AccessToken) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AccessToken with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AccessTokenMultiError, or
// nil if none found.
func (m *AccessToken) ValidateAll() error {
	return m.validate(true)
}

func (m *AccessToken) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for AccessToken

	// no validation rules for ExpiresIn

	if len(errors) > 0 {
		return AccessTokenMultiError(errors)
	}

	return nil
}

// AccessTokenMultiError is an error wrapping multiple validation errors
// returned by AccessToken.ValidateAll() if the designated constraints aren't met.
type AccessTokenMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AccessTokenMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AccessTokenMultiError) AllErrors() []error { return m }

// AccessTokenValidationError is the validation error returned by
// AccessToken.Validate if the designated constraints aren't met.
type AccessTokenValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessTokenValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessTokenValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessTokenValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessTokenValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessTokenValidationError) ErrorName() string { return "AccessTokenValidationError" }

// Error satisfies the builtin error interface
func (e AccessTokenValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessToken.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessTokenValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessTokenValidationError{}

// Validate checks the field values on AuthLoginRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AuthLoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthLoginRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthLoginRequestMultiError, or nil if none found.
func (m *AuthLoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthLoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetUsername()) < 1 {
		err := AuthLoginRequestValidationError{
			field:  "Username",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPassword()) < 1 {
		err := AuthLoginRequestValidationError{
			field:  "Password",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCaptcha()) < 1 {
		err := AuthLoginRequestValidationError{
			field:  "Captcha",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCaptchaVoucher()) < 1 {
		err := AuthLoginRequestValidationError{
			field:  "CaptchaVoucher",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AuthLoginRequestMultiError(errors)
	}

	return nil
}

// AuthLoginRequestMultiError is an error wrapping multiple validation errors
// returned by AuthLoginRequest.ValidateAll() if the designated constraints
// aren't met.
type AuthLoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthLoginRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthLoginRequestMultiError) AllErrors() []error { return m }

// AuthLoginRequestValidationError is the validation error returned by
// AuthLoginRequest.Validate if the designated constraints aren't met.
type AuthLoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthLoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthLoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthLoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthLoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthLoginRequestValidationError) ErrorName() string { return "AuthLoginRequestValidationError" }

// Error satisfies the builtin error interface
func (e AuthLoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthLoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthLoginRequestValidationError{}

// Validate checks the field values on AuthLoginResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AuthLoginResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthLoginResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthLoginResponseMultiError, or nil if none found.
func (m *AuthLoginResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthLoginResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAuth()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuthLoginResponseValidationError{
					field:  "Auth",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuthLoginResponseValidationError{
					field:  "Auth",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAuth()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuthLoginResponseValidationError{
				field:  "Auth",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Username

	if len(errors) > 0 {
		return AuthLoginResponseMultiError(errors)
	}

	return nil
}

// AuthLoginResponseMultiError is an error wrapping multiple validation errors
// returned by AuthLoginResponse.ValidateAll() if the designated constraints
// aren't met.
type AuthLoginResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthLoginResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthLoginResponseMultiError) AllErrors() []error { return m }

// AuthLoginResponseValidationError is the validation error returned by
// AuthLoginResponse.Validate if the designated constraints aren't met.
type AuthLoginResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthLoginResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthLoginResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthLoginResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthLoginResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthLoginResponseValidationError) ErrorName() string {
	return "AuthLoginResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AuthLoginResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthLoginResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthLoginResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthLoginResponseValidationError{}

// Validate checks the field values on AuthCaptchaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthCaptchaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthCaptchaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthCaptchaRequestMultiError, or nil if none found.
func (m *AuthCaptchaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthCaptchaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthCaptchaRequestMultiError(errors)
	}

	return nil
}

// AuthCaptchaRequestMultiError is an error wrapping multiple validation errors
// returned by AuthCaptchaRequest.ValidateAll() if the designated constraints
// aren't met.
type AuthCaptchaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthCaptchaRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthCaptchaRequestMultiError) AllErrors() []error { return m }

// AuthCaptchaRequestValidationError is the validation error returned by
// AuthCaptchaRequest.Validate if the designated constraints aren't met.
type AuthCaptchaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthCaptchaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthCaptchaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthCaptchaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthCaptchaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthCaptchaRequestValidationError) ErrorName() string {
	return "AuthCaptchaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AuthCaptchaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthCaptchaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthCaptchaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthCaptchaRequestValidationError{}

// Validate checks the field values on AuthCaptchaResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthCaptchaResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthCaptchaResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthCaptchaResponseMultiError, or nil if none found.
func (m *AuthCaptchaResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthCaptchaResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Voucher

	// no validation rules for Captcha

	if len(errors) > 0 {
		return AuthCaptchaResponseMultiError(errors)
	}

	return nil
}

// AuthCaptchaResponseMultiError is an error wrapping multiple validation
// errors returned by AuthCaptchaResponse.ValidateAll() if the designated
// constraints aren't met.
type AuthCaptchaResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthCaptchaResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthCaptchaResponseMultiError) AllErrors() []error { return m }

// AuthCaptchaResponseValidationError is the validation error returned by
// AuthCaptchaResponse.Validate if the designated constraints aren't met.
type AuthCaptchaResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthCaptchaResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthCaptchaResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthCaptchaResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthCaptchaResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthCaptchaResponseValidationError) ErrorName() string {
	return "AuthCaptchaResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AuthCaptchaResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthCaptchaResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthCaptchaResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthCaptchaResponseValidationError{}

// Validate checks the field values on AuthLogoutRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AuthLogoutRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthLogoutRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthLogoutRequestMultiError, or nil if none found.
func (m *AuthLogoutRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthLogoutRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthLogoutRequestMultiError(errors)
	}

	return nil
}

// AuthLogoutRequestMultiError is an error wrapping multiple validation errors
// returned by AuthLogoutRequest.ValidateAll() if the designated constraints
// aren't met.
type AuthLogoutRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthLogoutRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthLogoutRequestMultiError) AllErrors() []error { return m }

// AuthLogoutRequestValidationError is the validation error returned by
// AuthLogoutRequest.Validate if the designated constraints aren't met.
type AuthLogoutRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthLogoutRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthLogoutRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthLogoutRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthLogoutRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthLogoutRequestValidationError) ErrorName() string {
	return "AuthLogoutRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AuthLogoutRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthLogoutRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthLogoutRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthLogoutRequestValidationError{}

// Validate checks the field values on AuthLogoutResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthLogoutResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthLogoutResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthLogoutResponseMultiError, or nil if none found.
func (m *AuthLogoutResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthLogoutResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthLogoutResponseMultiError(errors)
	}

	return nil
}

// AuthLogoutResponseMultiError is an error wrapping multiple validation errors
// returned by AuthLogoutResponse.ValidateAll() if the designated constraints
// aren't met.
type AuthLogoutResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthLogoutResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthLogoutResponseMultiError) AllErrors() []error { return m }

// AuthLogoutResponseValidationError is the validation error returned by
// AuthLogoutResponse.Validate if the designated constraints aren't met.
type AuthLogoutResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthLogoutResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthLogoutResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthLogoutResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthLogoutResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthLogoutResponseValidationError) ErrorName() string {
	return "AuthLogoutResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AuthLogoutResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthLogoutResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthLogoutResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthLogoutResponseValidationError{}

// Validate checks the field values on AuthRefreshRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthRefreshRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthRefreshRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthRefreshRequestMultiError, or nil if none found.
func (m *AuthRefreshRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthRefreshRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthRefreshRequestMultiError(errors)
	}

	return nil
}

// AuthRefreshRequestMultiError is an error wrapping multiple validation errors
// returned by AuthRefreshRequest.ValidateAll() if the designated constraints
// aren't met.
type AuthRefreshRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthRefreshRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthRefreshRequestMultiError) AllErrors() []error { return m }

// AuthRefreshRequestValidationError is the validation error returned by
// AuthRefreshRequest.Validate if the designated constraints aren't met.
type AuthRefreshRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthRefreshRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthRefreshRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthRefreshRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthRefreshRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthRefreshRequestValidationError) ErrorName() string {
	return "AuthRefreshRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AuthRefreshRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthRefreshRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthRefreshRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthRefreshRequestValidationError{}

// Validate checks the field values on AuthRefreshResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthRefreshResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthRefreshResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthRefreshResponseMultiError, or nil if none found.
func (m *AuthRefreshResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthRefreshResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for ExpireIn

	if len(errors) > 0 {
		return AuthRefreshResponseMultiError(errors)
	}

	return nil
}

// AuthRefreshResponseMultiError is an error wrapping multiple validation
// errors returned by AuthRefreshResponse.ValidateAll() if the designated
// constraints aren't met.
type AuthRefreshResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthRefreshResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthRefreshResponseMultiError) AllErrors() []error { return m }

// AuthRefreshResponseValidationError is the validation error returned by
// AuthRefreshResponse.Validate if the designated constraints aren't met.
type AuthRefreshResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthRefreshResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthRefreshResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthRefreshResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthRefreshResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthRefreshResponseValidationError) ErrorName() string {
	return "AuthRefreshResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AuthRefreshResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthRefreshResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthRefreshResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthRefreshResponseValidationError{}

// Validate checks the field values on AuthDetailRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AuthDetailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthDetailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthDetailRequestMultiError, or nil if none found.
func (m *AuthDetailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthDetailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthDetailRequestMultiError(errors)
	}

	return nil
}

// AuthDetailRequestMultiError is an error wrapping multiple validation errors
// returned by AuthDetailRequest.ValidateAll() if the designated constraints
// aren't met.
type AuthDetailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthDetailRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthDetailRequestMultiError) AllErrors() []error { return m }

// AuthDetailRequestValidationError is the validation error returned by
// AuthDetailRequest.Validate if the designated constraints aren't met.
type AuthDetailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthDetailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthDetailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthDetailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthDetailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthDetailRequestValidationError) ErrorName() string {
	return "AuthDetailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AuthDetailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthDetailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthDetailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthDetailRequestValidationError{}

// Validate checks the field values on AuthDetailResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthDetailResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthDetailResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthDetailResponseMultiError, or nil if none found.
func (m *AuthDetailResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthDetailResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Username

	// no validation rules for Email

	// no validation rules for Mobile

	// no validation rules for Address

	// no validation rules for TwoFactorEnable

	if len(errors) > 0 {
		return AuthDetailResponseMultiError(errors)
	}

	return nil
}

// AuthDetailResponseMultiError is an error wrapping multiple validation errors
// returned by AuthDetailResponse.ValidateAll() if the designated constraints
// aren't met.
type AuthDetailResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthDetailResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthDetailResponseMultiError) AllErrors() []error { return m }

// AuthDetailResponseValidationError is the validation error returned by
// AuthDetailResponse.Validate if the designated constraints aren't met.
type AuthDetailResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthDetailResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthDetailResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthDetailResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthDetailResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthDetailResponseValidationError) ErrorName() string {
	return "AuthDetailResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AuthDetailResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthDetailResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthDetailResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthDetailResponseValidationError{}

// Validate checks the field values on AuthUpdatePasswordRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthUpdatePasswordRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthUpdatePasswordRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthUpdatePasswordRequestMultiError, or nil if none found.
func (m *AuthUpdatePasswordRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthUpdatePasswordRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetOldPassword()) < 6 {
		err := AuthUpdatePasswordRequestValidationError{
			field:  "OldPassword",
			reason: "value length must be at least 6 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetNewPassword()) < 6 {
		err := AuthUpdatePasswordRequestValidationError{
			field:  "NewPassword",
			reason: "value length must be at least 6 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AuthUpdatePasswordRequestMultiError(errors)
	}

	return nil
}

// AuthUpdatePasswordRequestMultiError is an error wrapping multiple validation
// errors returned by AuthUpdatePasswordRequest.ValidateAll() if the
// designated constraints aren't met.
type AuthUpdatePasswordRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthUpdatePasswordRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthUpdatePasswordRequestMultiError) AllErrors() []error { return m }

// AuthUpdatePasswordRequestValidationError is the validation error returned by
// AuthUpdatePasswordRequest.Validate if the designated constraints aren't met.
type AuthUpdatePasswordRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthUpdatePasswordRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthUpdatePasswordRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthUpdatePasswordRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthUpdatePasswordRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthUpdatePasswordRequestValidationError) ErrorName() string {
	return "AuthUpdatePasswordRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AuthUpdatePasswordRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthUpdatePasswordRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthUpdatePasswordRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthUpdatePasswordRequestValidationError{}

// Validate checks the field values on AuthUpdatePasswordResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthUpdatePasswordResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthUpdatePasswordResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthUpdatePasswordResponseMultiError, or nil if none found.
func (m *AuthUpdatePasswordResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthUpdatePasswordResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Username

	// no validation rules for Email

	// no validation rules for Mobile

	if len(errors) > 0 {
		return AuthUpdatePasswordResponseMultiError(errors)
	}

	return nil
}

// AuthUpdatePasswordResponseMultiError is an error wrapping multiple
// validation errors returned by AuthUpdatePasswordResponse.ValidateAll() if
// the designated constraints aren't met.
type AuthUpdatePasswordResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthUpdatePasswordResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthUpdatePasswordResponseMultiError) AllErrors() []error { return m }

// AuthUpdatePasswordResponseValidationError is the validation error returned
// by AuthUpdatePasswordResponse.Validate if the designated constraints aren't met.
type AuthUpdatePasswordResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthUpdatePasswordResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthUpdatePasswordResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthUpdatePasswordResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthUpdatePasswordResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthUpdatePasswordResponseValidationError) ErrorName() string {
	return "AuthUpdatePasswordResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AuthUpdatePasswordResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthUpdatePasswordResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthUpdatePasswordResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthUpdatePasswordResponseValidationError{}

// Validate checks the field values on AuthUpdateDetailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthUpdateDetailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthUpdateDetailRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthUpdateDetailRequestMultiError, or nil if none found.
func (m *AuthUpdateDetailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthUpdateDetailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Username

	// no validation rules for Mobile

	// no validation rules for Address

	if len(errors) > 0 {
		return AuthUpdateDetailRequestMultiError(errors)
	}

	return nil
}

// AuthUpdateDetailRequestMultiError is an error wrapping multiple validation
// errors returned by AuthUpdateDetailRequest.ValidateAll() if the designated
// constraints aren't met.
type AuthUpdateDetailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthUpdateDetailRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthUpdateDetailRequestMultiError) AllErrors() []error { return m }

// AuthUpdateDetailRequestValidationError is the validation error returned by
// AuthUpdateDetailRequest.Validate if the designated constraints aren't met.
type AuthUpdateDetailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthUpdateDetailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthUpdateDetailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthUpdateDetailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthUpdateDetailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthUpdateDetailRequestValidationError) ErrorName() string {
	return "AuthUpdateDetailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AuthUpdateDetailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthUpdateDetailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthUpdateDetailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthUpdateDetailRequestValidationError{}

// Validate checks the field values on AuthUpdateDetailResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AuthUpdateDetailResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthUpdateDetailResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthUpdateDetailResponseMultiError, or nil if none found.
func (m *AuthUpdateDetailResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthUpdateDetailResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthUpdateDetailResponseMultiError(errors)
	}

	return nil
}

// AuthUpdateDetailResponseMultiError is an error wrapping multiple validation
// errors returned by AuthUpdateDetailResponse.ValidateAll() if the designated
// constraints aren't met.
type AuthUpdateDetailResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthUpdateDetailResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthUpdateDetailResponseMultiError) AllErrors() []error { return m }

// AuthUpdateDetailResponseValidationError is the validation error returned by
// AuthUpdateDetailResponse.Validate if the designated constraints aren't met.
type AuthUpdateDetailResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthUpdateDetailResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthUpdateDetailResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthUpdateDetailResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthUpdateDetailResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthUpdateDetailResponseValidationError) ErrorName() string {
	return "AuthUpdateDetailResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AuthUpdateDetailResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthUpdateDetailResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthUpdateDetailResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthUpdateDetailResponseValidationError{}

// Validate checks the field values on Menus with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Menus) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Menus with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MenusMultiError, or nil if none found.
func (m *Menus) ValidateAll() error {
	return m.validate(true)
}

func (m *Menus) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Path

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetMeta()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MenusValidationError{
					field:  "Meta",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MenusValidationError{
					field:  "Meta",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMeta()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MenusValidationError{
				field:  "Meta",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, MenusValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, MenusValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return MenusValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return MenusMultiError(errors)
	}

	return nil
}

// MenusMultiError is an error wrapping multiple validation errors returned by
// Menus.ValidateAll() if the designated constraints aren't met.
type MenusMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MenusMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MenusMultiError) AllErrors() []error { return m }

// MenusValidationError is the validation error returned by Menus.Validate if
// the designated constraints aren't met.
type MenusValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MenusValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MenusValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MenusValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MenusValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MenusValidationError) ErrorName() string { return "MenusValidationError" }

// Error satisfies the builtin error interface
func (e MenusValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMenus.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MenusValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MenusValidationError{}

// Validate checks the field values on Meta with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Meta) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Meta with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MetaMultiError, or nil if none found.
func (m *Meta) ValidateAll() error {
	return m.validate(true)
}

func (m *Meta) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Icon

	// no validation rules for Title

	// no validation rules for Sort

	// no validation rules for Hidden

	// no validation rules for UseLayout

	// no validation rules for FrameSrc

	if len(errors) > 0 {
		return MetaMultiError(errors)
	}

	return nil
}

// MetaMultiError is an error wrapping multiple validation errors returned by
// Meta.ValidateAll() if the designated constraints aren't met.
type MetaMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MetaMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MetaMultiError) AllErrors() []error { return m }

// MetaValidationError is the validation error returned by Meta.Validate if the
// designated constraints aren't met.
type MetaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MetaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MetaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MetaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MetaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MetaValidationError) ErrorName() string { return "MetaValidationError" }

// Error satisfies the builtin error interface
func (e MetaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMeta.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MetaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MetaValidationError{}

// Validate checks the field values on AuthMenusRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AuthMenusRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthMenusRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthMenusRequestMultiError, or nil if none found.
func (m *AuthMenusRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthMenusRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return AuthMenusRequestMultiError(errors)
	}

	return nil
}

// AuthMenusRequestMultiError is an error wrapping multiple validation errors
// returned by AuthMenusRequest.ValidateAll() if the designated constraints
// aren't met.
type AuthMenusRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthMenusRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthMenusRequestMultiError) AllErrors() []error { return m }

// AuthMenusRequestValidationError is the validation error returned by
// AuthMenusRequest.Validate if the designated constraints aren't met.
type AuthMenusRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthMenusRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthMenusRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthMenusRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthMenusRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthMenusRequestValidationError) ErrorName() string { return "AuthMenusRequestValidationError" }

// Error satisfies the builtin error interface
func (e AuthMenusRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthMenusRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthMenusRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthMenusRequestValidationError{}

// Validate checks the field values on AuthMenusResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AuthMenusResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthMenusResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthMenusResponseMultiError, or nil if none found.
func (m *AuthMenusResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthMenusResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AuthMenusResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AuthMenusResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AuthMenusResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return AuthMenusResponseMultiError(errors)
	}

	return nil
}

// AuthMenusResponseMultiError is an error wrapping multiple validation errors
// returned by AuthMenusResponse.ValidateAll() if the designated constraints
// aren't met.
type AuthMenusResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthMenusResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthMenusResponseMultiError) AllErrors() []error { return m }

// AuthMenusResponseValidationError is the validation error returned by
// AuthMenusResponse.Validate if the designated constraints aren't met.
type AuthMenusResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthMenusResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthMenusResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthMenusResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthMenusResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthMenusResponseValidationError) ErrorName() string {
	return "AuthMenusResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AuthMenusResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthMenusResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthMenusResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthMenusResponseValidationError{}
